# Generated by Django 4.2.6 on 2023-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datetime_deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
