# Generated by Django 4.2.6 on 2023-10-05 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0002_alter_task_datetime_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="is_done",
        ),
    ]
