# Generated by Django 4.2.6 on 2023-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0003_rename_status_task_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datetime_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
